CREATE SEQUENCE RECORD_ID_S START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER populate_record_id
  BEFORE INSERT ON GL_INTERFACE_STG
  FOR EACH ROW
BEGIN
  SELECT RECORD_ID_S.nextval, SYSDATE
    INTO :new.record_id, :new.data_load_date
    FROM dual;
END;