CREATE USER adb_user IDENTIFIED BY Password1234;
GRANT CREATE SESSION TO adb_user;

--DROP USER adb_user CASCADE;

GRANT UNLIMITED TABLESPACE TO adb_user;
GRANT CREATE ANALYTIC VIEW TO adb_user;
GRANT CREATE ATTRIBUTE DIMENSION TO adb_user;
GRANT ALTER SESSION TO adb_user;
GRANT CREATE HIERARCHY TO adb_user;
GRANT CREATE JOB TO adb_user;
GRANT CREATE MATERIALIZED VIEW TO adb_user;
GRANT CREATE MINING MODEL TO adb_user;
GRANT CREATE PROCEDURE TO adb_user;
GRANT CREATE SEQUENCE TO adb_user;
GRANT CREATE SESSION TO adb_user;
GRANT CREATE SYNONYM TO adb_user;
GRANT CREATE TABLE TO adb_user;
GRANT CREATE TRIGGER TO adb_user;
GRANT CREATE TYPE TO adb_user;
GRANT CREATE VIEW TO adb_user;
--GRANT READ,WRITE ON directory STAGE_DIR TO adb_user;
--GRANT EXECUTE ON DBMS_CLOUD TO adb_user;
--grant EXECUTE privilege on OCI PL/SQL SDK to adb_user;
