CREATE TABLE GL_DAILY_RATES_STG(
    FROM_CURRENCY_CODE    VARCHAR2(10)
  , TO_CURRENCY_CODE      VARCHAR2(10)
  , CONVERSION_RATE       VARCHAR2(100)
  , FROM_CONVERSION_DATE  DATE
  , TO_CONVERSION_DATE    DATE
  , CONVERSION_RATE       NUMBER
  , INVERSE_RATE          NUMBER
  , DATA_LOAD_DATE        DATE
  , RECORD_ID             NUMBER
);
